# Generated by Django 3.2.13 on 2022-05-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_clockedtask_interval_periodictasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockedtask',
            name='timetorun',
            field=models.DateTimeField(),
        ),
    ]
