# Generated by Django 3.2.13 on 2022-05-03 08:15

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import schedules.enum


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('schedules', '0003_alter_clockedtask_timetorun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('status', enumchoicefield.fields.EnumChoiceField(default=schedules.enum.SetupStatus['active'], enum_class=schedules.enum.SetupStatus, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_interval', enumchoicefield.fields.EnumChoiceField(default=schedules.enum.TimeInterval['five_mins'], enum_class=schedules.enum.TimeInterval, max_length=9)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setups',
            },
        ),
    ]
