# Generated by Django 3.2.13 on 2022-05-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('schedules', '0004_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictasks',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=100),
        ),
        migrations.AddField(
            model_name='periodictasks',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
        migrations.RemoveField(
            model_name='periodictasks',
            name='command',
        ),
        migrations.AddField(
            model_name='periodictasks',
            name='command',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.schedulecommand'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Setup',
        ),
    ]
