# Generated by Django 3.2.13 on 2022-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20220507_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictasks',
            name='registered_task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='periodictasks',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100),
        ),
    ]
