# Generated by Django 3.2.13 on 2022-05-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20220515_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='periodictasks',
            name='registered_task',
        ),
    ]
